name: 'Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
