name: 'Bump Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: 'NPM Publish'
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
