name: 'Publish'

on:
  workflow_run:
    workflows: ["Version"]
    types: [completed]

jobs:
  publish:
    name: 'NPM Publish'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
